"""added lesson foreign key to progress

Revision ID: 28cc2156508b
Revises: d643650edb99
Create Date: 2020-11-30 19:35:10.041101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28cc2156508b'
down_revision = 'd643650edb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_actual_progress', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'step_actual_progress', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step_actual_progress', type_='foreignkey')
    op.drop_column('step_actual_progress', 'lesson_id')
    # ### end Alembic commands ###
