"""Added announcement table

Revision ID: 7eff3131328d
Revises: d643650edb99
Create Date: 2020-12-04 09:21:04.547472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eff3131328d'
down_revision = 'd643650edb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(length=1000), nullable=True),
    sa.Column('message', sa.String(length=10000), nullable=True),
    sa.Column('for_all', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'step_actual_progress', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'step_actual_progress', type_='foreignkey')
    op.drop_table('announcement')
    # ### end Alembic commands ###
