"""Adding email confirmation

Revision ID: ad88eb2d7517
Revises: 70feec282913
Create Date: 2020-10-13 10:51:26.826688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad88eb2d7517'
down_revision = '70feec282913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_confirmation_sent_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email_confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_confirmed_on')
    op.drop_column('user', 'email_confirmed')
    op.drop_column('user', 'email_confirmation_sent_on')
    # ### end Alembic commands ###
