"""empty message

Revision ID: b880b44f8363
Revises: 
Create Date: 2020-10-26 14:11:32.768002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b880b44f8363'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academy_name'), 'academy', ['name'], unique=True)
    op.create_table('length_of_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_length_of_class_name'), 'length_of_class', ['name'], unique=True)
    op.create_table('permission_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_name'), 'step', ['name'], unique=True)
    op.create_table('studentonclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentonclass2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_of_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_of_class_name'), 'type_of_class', ['name'], unique=True)
    op.create_table('classes121',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TypeOfClass', sa.String(length=20), nullable=True),
    sa.Column('length_of_class', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['length_of_class'], ['length_of_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_actual_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length_of_class', sa.Integer(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['length_of_class'], ['length_of_class.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step_expected_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length_of_class', sa.Integer(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['length_of_class'], ['length_of_class.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('email_confirmation_sent_on', sa.DateTime(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('email_confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    op.create_index(op.f('ix_user_position'), 'user', ['position'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('class121',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('what_was_done', sa.String(length=500), nullable=True),
    sa.Column('exercises_done', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('classes121_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classes121_id'], ['classes121.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class121_exercises_done'), 'class121', ['exercises_done'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('time', sa.String(length=128), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('amount_of_students', sa.Integer(), nullable=True),
    sa.Column('class_number', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('length_of_class', sa.Integer(), nullable=True),
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('type_of_class', sa.Integer(), nullable=True),
    sa.Column('classes121_id', sa.Integer(), nullable=True),
    sa.Column('student_on_class', sa.Integer(), nullable=True),
    sa.Column('student_on_class2', sa.Integer(), nullable=True),
    sa.Column('step_expected_id', sa.Integer(), nullable=True),
    sa.Column('step_actual_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], ),
    sa.ForeignKeyConstraint(['classes121_id'], ['classes121.id'], ),
    sa.ForeignKeyConstraint(['length_of_class'], ['length_of_class.id'], ),
    sa.ForeignKeyConstraint(['step_actual_id'], ['step_actual_tracker.id'], ),
    sa.ForeignKeyConstraint(['step_expected_id'], ['step_expected_tracker.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.ForeignKeyConstraint(['student_on_class'], ['studentonclass.id'], ),
    sa.ForeignKeyConstraint(['student_on_class2'], ['studentonclass2.id'], ),
    sa.ForeignKeyConstraint(['type_of_class'], ['type_of_class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_name'), 'lessons', ['name'], unique=False)
    op.create_index(op.f('ix_lessons_time'), 'lessons', ['time'], unique=False)
    op.create_table('step_actual_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=True),
    sa.Column('lesson_number', sa.Integer(), nullable=True),
    sa.Column('last_page', sa.Integer(), nullable=True),
    sa.Column('last_word', sa.String(length=40), nullable=True),
    sa.Column('exercises', sa.String(length=100), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('step_actual_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['step_actual_id'], ['step_actual_tracker.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_actual_progress_class_number'), 'step_actual_progress', ['class_number'], unique=False)
    op.create_index(op.f('ix_step_actual_progress_lesson_number'), 'step_actual_progress', ['lesson_number'], unique=False)
    op.create_table('step_expected_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_number', sa.Integer(), nullable=True),
    sa.Column('lesson_number', sa.Integer(), nullable=True),
    sa.Column('last_page', sa.Integer(), nullable=True),
    sa.Column('last_word', sa.String(length=40), nullable=True),
    sa.Column('exercises', sa.String(length=100), nullable=True),
    sa.Column('step_expected_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['step_expected_id'], ['step_expected_tracker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_expected_progress_class_number'), 'step_expected_progress', ['class_number'], unique=False)
    op.create_index(op.f('ix_step_expected_progress_lesson_number'), 'step_expected_progress', ['lesson_number'], unique=False)
    op.create_table('trained_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('teacher', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_permissions',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE')
    )
    op.create_index(op.f('ix_user_permissions_permission_id'), 'user_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.create_table('days_done',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('lessons', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lessons'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('days_missed', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('student_on_class', sa.Integer(), nullable=True),
    sa.Column('student_on_class2', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('academy_id', sa.Integer(), nullable=True),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['academy_id'], ['academy.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['step.id'], ),
    sa.ForeignKeyConstraint(['student_on_class'], ['studentonclass.id'], ),
    sa.ForeignKeyConstraint(['student_on_class2'], ['studentonclass2.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    op.create_index(op.f('ix_student_name'), 'student', ['name'], unique=True)
    op.create_index(op.f('ix_student_phone'), 'student', ['phone'], unique=True)
    op.create_table('step_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.Column('end_of_step_writing', sa.Integer(), nullable=True),
    sa.Column('end_of_step_speaking', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_marks')
    op.drop_index(op.f('ix_student_phone'), table_name='student')
    op.drop_index(op.f('ix_student_name'), table_name='student')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_table('student')
    op.drop_table('days_done')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_permission_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_table('trained_in')
    op.drop_index(op.f('ix_step_expected_progress_lesson_number'), table_name='step_expected_progress')
    op.drop_index(op.f('ix_step_expected_progress_class_number'), table_name='step_expected_progress')
    op.drop_table('step_expected_progress')
    op.drop_index(op.f('ix_step_actual_progress_lesson_number'), table_name='step_actual_progress')
    op.drop_index(op.f('ix_step_actual_progress_class_number'), table_name='step_actual_progress')
    op.drop_table('step_actual_progress')
    op.drop_index(op.f('ix_lessons_time'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_name'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_class121_exercises_done'), table_name='class121')
    op.drop_table('class121')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_position'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('step_expected_tracker')
    op.drop_table('step_actual_tracker')
    op.drop_table('classes121')
    op.drop_index(op.f('ix_type_of_class_name'), table_name='type_of_class')
    op.drop_table('type_of_class')
    op.drop_table('studentonclass2')
    op.drop_table('studentonclass')
    op.drop_index(op.f('ix_step_name'), table_name='step')
    op.drop_table('step')
    op.drop_table('permission_groups')
    op.drop_index(op.f('ix_length_of_class_name'), table_name='length_of_class')
    op.drop_table('length_of_class')
    op.drop_index(op.f('ix_academy_name'), table_name='academy')
    op.drop_table('academy')
    # ### end Alembic commands ###
